### ISSUE TITLE
Message Scope appears to treat independent writes as two messages

### ISSUE THREAD

**Issue by mosminer** [MilesEngineering/MsgTools#18] opened 2017-11-21 21:55 UTC
If I do two TCP sends - one for the header, and a second for the payload of the message, message scope appears to treat this as two separate messages.  You will get one of the right type, and a second of an unknown type.  I'm testing from Android/Java.

**Comment by mgazic** [comment] 2017-11-21 22:04
Duplicate of #17

**Closed by mgazic** 2017-11-21 22:04 UTC
